on load:
#    set {skript::lastLoader} to player
#    set {skript::lastFile} to name of script
#    set {skript::lastPath} to path of script
    send "" to all players
    send "<##FFFF55>&lM<##FFFF6A>&lU<##FFFF80>&lT<##FFFF95>&lL<##FFFFAA>&lI<##FFFFBF>&lF<##FFFFD5>&lA<##FFFFEA>&lR<##FFFFFF>&lM<##FFFFFF>&lE<##FFFFFF>&lR &7Reloaded &e/MultiFarmer/principal/sb&f.sk" to all players
    send "" to all players

every 2 seconds:
    loop all players:
        set {_progress} to (({level::playerExp::%uuid of loop-player%} / {level::xptolevel::%uuid of loop-player%}) * 100)
        set {_level} to {level::playerLevel::%uuid of loop-player%}
        set {_playermultiplier} to {season1PlayerMultiplier::%uuid of loop-player%}
        set {_kills} to {season1PlayerKills::%uuid of loop-player%}
        set {_global} to {global blocks}
        set {_tokens} to {season1PlayerToken::%uuid of loop-player%}
        set {_playersblock} to {season1blocks::%uuid of loop-player%}
        set {_blockrank} to 1
        set {_globalblocks} to 0
        set {_prestige} to {season1PlayerPrestige::%uuid of loop-player%}
        set {_group} to group of loop-player
        if {_group} is "ultimate":
            set {_rankmulti} to "&c* 1.25"
        else if {_group} is "champion":
            set {_rankmulti} to "&c* 1.5"
        else if {_group} is "royal":
            set {_rankmulti} to "&c* 1.75"
        else if {_group} is "guardian":
            set {_rankmulti} to "&c* 2"
        else if {_group} is "angel":
            set {_rankmulti} to "&c* 3"
        loop all players:
            if {season1blocks::%uuid of loop-player-2%} >= 1000000000:
                set {_amount} to ({season1blocks::%uuid of loop-player-2%} / 1000000000)
                set {formatted_block::%uuid of loop-player-2%} to "%{_amount}%B"
            else if {season1blocks::%uuid of loop-player-2%} >= 1000000:
                set {_amount} to ({season1blocks::%uuid of loop-player-2%} / 1000000)
                set {formatted_block::%uuid of loop-player-2%} to "%{_amount}%M"
            else if {season1blocks::%uuid of loop-player-2%} >= 1000:
                set {_amount} to ({season1blocks::%uuid of loop-player-2%} / 1000)
                set {formatted_block::%uuid of loop-player-2%} to "%{_amount}%K"
            else if {season1blocks::%uuid of loop-player-2%} < 1000:
                set {formatted_block::%uuid of loop-player-2%} to "%{_amount}%"

            if {season1PlayerToken::%uuid of loop-player-2%} >= 1000000000:
                set {_amount} to ({season1PlayerToken::%uuid of loop-player-2%} / 1000000000)
                set {formatted_token::%uuid of loop-player-2%} to "%{_amount}%B"
            else if {season1PlayerToken::%uuid of loop-player-2%} >= 1000000:
                set {_amount} to ({season1PlayerToken::%uuid of loop-player-2%} / 1000000)
                set {formatted_token::%uuid of loop-player-2%} to "%{_amount}%M"
            else if {season1PlayerToken::%uuid of loop-player-2%} >= 1000:
                set {_amount} to ({season1PlayerToken::%uuid of loop-player-2%} / 1000)
                set {formatted_token::%uuid of loop-player-2%} to "%{_amount}%K"
            else if {season1PlayerToken::%uuid of loop-player-2%} < 1000:
                set {formatted_token::%uuid of loop-player-2%} to "%{_amount}%"

#            loop {player's uuids::*}:
#                set {_uuid} to loop-value-3
#                set {_blockCounter} to {player's block counter::%{_uuid}%}
#                if {_blockCounter} is a number:
#                    add {_blockCounter} to {_globalblocks}
#                    if {_globalblocks} >= 1000000000:
#                        set {_block} to ({_globalblocks} / 1000000000)
#                        set {_formatted_block} to "%{_block}%B"
#                    else if {_globalblocks} >= 1000000:
#                        set {_block} to ({_globalblocks} / 1000000)
#                        set {_formatted_block} to "%{_block}%M"
#                    else if {_globalblocks} >= 1000:
#                        set {_block} to ({_globalblocks} / 1000)
#                        set {_formatted_block} to "%{_block}%K"
#                    else:
#                        set {_formatted_block} to {_globalblocks}
#                    set {formatted_block} to {_formatted_block}

#            if {_playerblock} < {player's block counter::%uuid of loop-player-2%}:
#                add 1 to {_blockrank}

        wipe loop-player's sidebar
        set name of sidebar of loop-player to "&x&F&F&F&F&5&5ᴍ&x&F&F&F&F&6&Aᴜ&x&F&F&F&F&8&0ʟ&x&F&F&F&F&9&5ᴛ&x&F&F&F&F&A&Aɪ&x&F&F&F&F&B&Fꜰ&x&F&F&F&F&D&5ᴀ&x&F&F&F&F&E&Aʀ&x&F&F&F&F&F&Fᴍ&x&F&F&F&F&F&Fᴇ&x&F&F&F&F&F&Fʀ"#&r &7(&a%number of players%&7/&a100&7)"
        set score "‌‌ " in sidebar of loop-player to 12
        set score "&e«&e&m                          &e»" in sidebar of loop-player to 11
        set score "&e◆ &7ʟᴇᴠᴇʟ &8[&a%{_level}%&8]" in sidebar of loop-player to 10
        if {_progress} <= 5:
            set score "&8&m                   &r &7[%{_progress}%%%]" in sidebar of loop-player to 9
        else if {_progress} <= 10:
            set score "&a&m &m&8&m                  &r &7[%{_progress}%%%]" in sidebar of loop-player to 9
        else if {_progress} <= 15:
            set score "&a&m  &m&8&m                 &r &7[%{_progress}%%%]" in sidebar of loop-player to 9
        else if {_progress} <= 20:
            set score "&a&m   &m&8&m                &r &7[%{_progress}%%%]" in sidebar of loop-player to 9
        else if {_progress} <= 25:
            set score "&a&m    &m&8&m               &r &7[%{_progress}%%%]" in sidebar of loop-player to 9
        else if {_progress} <= 30:
            set score "&a&m     &m&8&m              &r &7[%{_progress}%%%]" in sidebar of loop-player to 9
        else if {_progress} <= 35:
            set score "&a&m      &m&8&m             &r &7[%{_progress}%%%]" in sidebar of loop-player to 9
        else if {_progress} <= 40:
            set score "&a&m       &m&8&m            &r &7[%{_progress}%%%]" in sidebar of loop-player to 9
        else if {_progress} <= 45:
            set score "&a&m        &m&8&m           &r &7[%{_progress}%%%]" in sidebar of loop-player to 9
        else if {_progress} <= 50:
            set score "&a&m         &m&8&m          &r &7[%{_progress}%%%]" in sidebar of loop-player to 9
        else if {_progress} <= 55:
            set score "&a&m          &m&8&m         &r &7[%{_progress}%%%]" in sidebar of loop-player to 9
        else if {_progress} <= 60:
            set score "&a&m           &m&8&m        &r &7[%{_progress}%%%]" in sidebar of loop-player to 9
        else if {_progress} <= 65:
            set score "&a&m            &m&8&m       &r &7[%{_progress}%%%]" in sidebar of loop-player to 9
        else if {_progress} <= 70:
            set score "&a&m             &m&8&m      &r &7[%{_progress}%%%]" in sidebar of loop-player to 9
        else if {_progress} <= 75:
            set score "&a&m              &m&8&m     &r &7[%{_progress}%%%]" in sidebar of loop-player to 9
        else if {_progress} <= 80:
            set score "&a&m               &m&8&m    &r &7[%{_progress}%%%]" in sidebar of loop-player to 9
        else if {_progress} <= 85:
            set score "&a&m                &m&8&m   &r &7[%{_progress}%%%]" in sidebar of loop-player to 9
        else if {_progress} <= 90:
            set score "&a&m                 &m&8&m  &r &7[%{_progress}%%%]" in sidebar of loop-player to 9
        else if {_progress} <= 95:
            set score "&a&m                  &m&8&m &r &7[%{_progress}%%%]" in sidebar of loop-player to 9
        else if {_progress} <= 100:
            set score "&a&m                   &r &7[%{_progress}%]" in sidebar of loop-player to 9
        if {_rankmulti} is set:
            set score "&e◆ &7ᴍᴜʟᴛɪᴘʟɪᴇʀ &d%{_playermultiplier}%x %{_rankmulti}%" in sidebar of loop-player to 8
        else if {_rankmulti} is not set:
            set score "&e◆ &7ᴍᴜʟᴛɪᴘʟɪᴇʀ &d%{_playermultiplier}%x" in sidebar of loop-player to 8
        set score "&e◆ &7ᴛᴏᴋᴇɴꜱ &e⛃%{formatted_token::%uuid of loop-player%}%" in sidebar of loop-player to 7
        set score "&e◆ &7ᴋɪʟʟꜱ &4🗡%{_kills}%" in sidebar of loop-player to 6
        set score "&e◆ &7ʙʟᴏᴄᴋꜱ &6🧱%{formatted_block::%uuid of loop-player%}%" in sidebar of loop-player to 5
        set score "&e◆ &7ᴘʀᴇꜱᴛɪɢᴇ &9🌀%{_prestige}%" in sidebar of loop-player to 4
        set score "&e◆ &7ʙᴏᴏꜱᴛᴇʀ &b⚡%{boosterplayers}%/50" in sidebar of loop-player to 3
        set score "&e«&e&m                          &r&e»" in sidebar of loop-player to 2
#        set score " &f・ &7ʀᴀɴᴋ &c%{_blockrank}%" in sidebar of loop-player to 2
        set score "‌  " in sidebar of loop-player to 1
        set score "&7ᴍᴜʟᴛɪꜰᴀʀᴍᴇʀ.ᴍɪɴᴇʜᴜᴛ.ɢɢ" in sidebar of loop-player to 0

function sbprefix(p: player):
    set {_group} to group of {_p}
    if {_group} is "default":
        set {sbprefix::%uuid of {_p}%} to "&8[MEMBER]"
    else if {_group} is "helper":
        set {sbprefix::%uuid of {_p}%} to "&x&5&6&&C&4&D[HELPER]"
    else if {_group} is "moderator":
        set {sbprefix::%uuid of {_p}%} to "&x&4&0&2&D&B&A[MOD]"
    else if {_group} is "manager":
        set {sbprefix::%uuid of {_p}%} to "&x&D&D&F&F&6&0[MANAGER]"
    else if {_group} is "owner":
        set {sbprefix::%uuid of {_p}%} to "[OWNER]"

on join:
    if {season1PlayerMultiplier::%uuid of player%} is not set:
        set {season1PlayerMultiplier::%uuid of player%} to 1
    if {season1PlayerToken::%uuid of player%} is not set:
        set {season1PlayerToken::%uuid of player%} to 0
    if {season1PlayerBlocks::%uuid of player%} is not set:
        set {season1PlayerBlocks::%uuid of player%} to 0
    if {season1PlayerPrestige::%uuid of player%} is not set:
        set {season1PlayerPrestige::%uuid of player%} to 0
    if {boosterplayers} is not set:
        set {boosterplayers} to 0
    
    if player has not played before:
        add 1 to {boosterplayers}
    if {boosterplayers} = 50:
        set {boosterplayers} to 0
        